version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
    depends_on:
      - db
      - jaeger
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=postgres;Username=postgres;Password=postgres"
      Jaeger__Protocol: http
      Jaeger__Port: 5317
      Jaeger__Host: jaeger
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
      - "17686:16686"
      - "14268:14268"
#      - "14269:14269"
      - "14250:14250"
#      - "9411:9411"
#      - "4317:4317"
#      - "5318:4318"
    command:
      - --log-level=warn
      - --collector.grpc.tls.enabled=true      
    volumes:
      - jaegerdata:/tmp
  
  opentelemetry:
    image: otel/opentelemetry-collector-contrib
    ports:
#      - "1888:1888" # pprof extension
#      - "8888:8888" # Prometheus metrics exposed by the Collector
#      - "8889:8889" # Prometheus exporter metrics
#      - "13133:13133" # health_check extension
#      - "4317:4317" # OTLP gRPC receiver
      - "5317:4317" # OTLP gRPC receiver
#      - "4318:4318" # OTLP http receiver
      - "5318:4318" # OTLP http receiver
#      - "55679:55679" # zpages extension
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317
    depends_on:
      jaeger:
        condition: service_started

volumes:
  pgdata:
    external: false
  jaegerdata:
    external: false